"""add unique constraint to product name

Revision ID: 6cc1669b4e8c
Revises: 7fb44aa4c22a
Create Date: 2026-08-26 17:09:08.116081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cc1669b4e8c'
down_revision: Union[str, Sequence[str], None] = '7fb44aa4c22a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_product_name', 'products', ['name'])
    op.create_unique_constraint(None, 'products', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_constraint('uq_product_name', 'products', type_='unique')
    # ### end Alembic commands ###
